### ISSUE TITLE
v0.13.0-beta feedback

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#136]
Do not hesitate to also comment if everything works so I know that somebody tested it, thanks 😃 

Downloads here: https://github.com/tomblachut/svelte-intellij/releases/tag/v0.13.0-beta

Please attach text snippets AND screenshots/recordings where applicable

**Comment by russelgal** [comment]
WebStorm 2020.2
Build #WS-202.6397.88, built on July 25, 2020
Subscription expired on June 13, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12


<details>
  <summary>Stacktrace</summary>

```java.lang.AssertionError: (788,788), text: {#if name}
    <h3>
        Form
        <b>{name}</b>
    </h3>
{:else}{/if}, language = Language: SvelteHTML
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:180)
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:104)
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:85)
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:70)
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:57)
	at dev.blachut.svelte.lang.editor.SvelteFoldingBuilder.appendBlockDescriptors(SvelteFoldingBuilder.kt:49)
	at dev.blachut.svelte.lang.editor.SvelteFoldingBuilder.doAddForChildren(SvelteFoldingBuilder.kt:18)
	at com.intellij.lang.XmlCodeFoldingBuilder.buildLanguageFoldRegions(XmlCodeFoldingBuilder.java:74)
	at com.intellij.lang.folding.CustomFoldingBuilder.buildFoldRegions(CustomFoldingBuilder.java:44)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:92)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:75)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:261)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:228)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:134)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:52)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$0(AsyncEditorLoader.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$1(AsyncEditorLoader.java:93)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:498)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$2(NonBlockingReadActionImpl.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:56)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:56)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:463)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$0(NonBlockingReadActionImpl.java:387)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by tomblachut** [comment]
@russelgal can you paste your code? Also what was the last action you did before this error?

**Comment by r00t3g** [comment]
I am not sure if it was planned to be fixed, however, named imports usages are still not recognised when used only with reactive prefixes:
![image](https://user-images.githubusercontent.com/579779/89504805-4ee52c00-d7d1-11ea-9d61-70467802e5d1.png)

**Comment by tomblachut** [comment]
@r00t3g sadly nothing about that was done for now. Basically `Find usages` is broken for auto subscriptions

**Comment by r00t3g** [comment]
Single-line script blocks get impromerly formatted - closing </script> tag sticks to the end of the code line. Does not occur when there are more that one line in the block

![codeformat](https://user-images.githubusercontent.com/579779/89509300-d2098080-d7d7-11ea-9c9f-c3a6a560d44e.gif)

**Comment by tomblachut** [comment]
@r00t3g 
![Screen Recording 2020-08-06 at 21 24 16](https://user-images.githubusercontent.com/615013/89573889-97313800-d82b-11ea-949f-e41ccdcb2d56.gif)

This is weird, actually `Optimize imports` is removing new line for some reason. Thx for finding it.

BTW why didn't you open issue for `svelte-preprocess` attributes sooner? ;)

**Comment by r00t3g** [comment]
@tomblachut 
> BTW why didn't you open issue for `svelte-preprocess` attributes sooner? ;)

I've been working through the module structure for a new project at its very early stage, so I just don't pay enough attention to styles yet to spot the issue. 😁 The module from the screencap is just a part of experimental playground for sapper.

**Comment by shirotech** [comment]
A minor issue which wasn't there prior to v0.12

<img width="367" alt="Screen Shot 2020-08-09 at 3 05 12 pm" src="https://user-images.githubusercontent.com/1149825/89725347-e35dc180-da51-11ea-915a-9a8df0d1d9c7.png">

When using detect import, the variable shouldn't be red. It should be yellow with an underline to indicate there are imports available.

**Comment by tomblachut** [comment]
@shirotech actually I changed it on purpose. Reasoning:
* TS always highlighted those in red
* JS is more permitting because WS can't definitely know that symbol isn't somehow added to global scope
* Svelte is a compiler with global symbol whitelist, so such debounceLazy definitely won't work without import - hence error
* I like it more, to be completely honest

Correct me if I'm wrong ofc.

**Comment by shirotech** [comment]
Cool that makes sense, just highlighting the difference just incass it was missed. Actually I like that as well, more aware of actual errors.
